# Generated by Django 2.0.13 on 2020-03-22 00:55

import api.utils
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('restaurant_location', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 3, 22, 0, 55, 6, 312058))),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email_id', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('password_hash', models.CharField(max_length=200)),
                ('user_type', models.CharField(choices=[('0', 'Customer'), ('1', 'Restaurant')], default=api.utils.UserType('0'), max_length=1)),
                ('is_veg', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 3, 22, 0, 55, 6, 310203))),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 3, 22, 0, 55, 6, 310234))),
            ],
        ),
    ]
