# Generated by Django 2.0.13 on 2020-03-22 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200322_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 1, 0, 8, 50082)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 1, 0, 8, 48907)),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 1, 0, 8, 48873)),
        ),
    ]
