# Generated by Django 2.0.13 on 2020-03-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200322_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='user_name',
        ),
    ]
