# Generated by Django 2.0.13 on 2020-03-23 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_restaurant_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='user_id',
        ),
        migrations.AddField(
            model_name='users',
            name='restaurant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Restaurant'),
        ),
    ]
